name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Ensure Gradle Wrapper is Executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
      continue-on-error: true  # This allows the workflow to continue even if the build fails

    - name: View Gradle Build Logs
      if: failure()  # Only run if the build fails
      run: cat build/reports/tests/test/index.html  # Adjust path to view test reports if available

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run tests with Gradle
      run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to staging environment
      run: echo "Deploying to staging environment..."
