name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B compile --file pom.xml
      continue-on-error: true  # Allow the workflow to continue even if this step fails

    - name: View Build Logs
      if: failure()  # Run only if previous steps failed
      run: cat target/*.log  # Adjust path if necessary to view build logs

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test with Maven
      run: mvn test
      continue-on-error: true  # Allow the workflow to continue even if this step fails

    - name: View Test Logs
      if: failure()  # Run only if previous steps failed
      run: cat target/test-classes/test.log  # Adjust path if necessary to view test logs

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Package with Maven
      run: mvn -B package --file pom.xml
      continue-on-error: true  # Allow the workflow to continue even if this step fails

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/*.jar

  notify:
    runs-on: ubuntu-latest
    needs: package
    if: success()  # Only run if the package job succeeds

    steps:
    - name: Notify Teams
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}  # Store your webhook URL in GitHub Secrets
      run: |
        curl -H 'Content-Type: application/json' \
             -X POST \
             -d '{"text": "Build and deployment succeeded! 🚀"}' \
             $TEAMS_WEBHOOK_URL
